import matplotlib.pyplot as mtp
'''
APÓS SER FEITA A INSTALAÇÃO DA BIBLIOTECA VIA CMD, ATRAVÉS DO COMANDO 'pip install matplotlib', FAZEMOS A IMPORTAÇÃO DA BIBLIOTECA COM O COMANDO ACIMA.
'''

estudantes = ['Maria', 'Iury', 'Diego', 'Carlos', 'Jacob', 'Eleonor']
notas = [10.0, 8.9, 7.5, 8.0, 9.2, 7.8]

mtp.bar(x = estudantes, height = notas)

'''
É MUITO IMPORTANTE QUE, AO FAZER USO DE UMA BIBLIOTECA PYTHON, PROCURE A DOCUMENTAÇÃO REFERENTE ÀQUELA BIBLIOTECA. CONHECER MELHOR SEUS MÉTODOS E COMO ELES FUNCIONAM SÃO ESSENCIAS
PARA TIRAR MAIOR PROVEITO.
ESSA FUNÇÃO 'BAR()', POR EXEMPLO, GERA UM GRÁFICO DE BARRA COM BASE NAS INFORMAÇÕES PASSADAS.
'''

#IMPORTANTO UMA FUNÇÃO ESPECÍFICA DE UMA BIBLIOTECA
from random import choice

'''
DESSA FORMA, FAZEMOS A IMPORTAÇÃO DE APENAS UMA FUNÇÃO DA BIBLIOTECA. ISSO É MUITO INTERESSANTE PARA EVITAR IMPORTAR BIBLIOTECAS MUITO PESADAS E QUE NECESSITARIAM DE APENAS UMA OU
OUTRA FUNÇÃO.
'''

print(choice([1, 2, 3, 4, 5, 6, 7, 8]))