import pyautogui    as pa
'''
A BIBLIOTECA PYAUTOGUI É USADA PARA FAZER A AUTOMATIZAÇÃO DE PROCESSOS VIA PYTHON, PODENDO SIMULAR CLIQUES DO MOUSE E ATALHOS DE TECLADO, POR EXEMPLO, PARA TORNAR PROCESSOS MAIS ÁGEIS.
VEJAMOS ALGUNS EXEMPLOS DE USO DA BIBLIOTECA, FAZENDO A AUTOMATIZAÇÃO DO CADASTRO DES PRODUTOS EM UMA TABELA SQL
'''
import time
'''
A BIBLIOTECA TIME SERÁ USADA PARA SETAR UM INTERVALO DE TEMPO DURANTE O CÓDIGO COM O MÉTODO SLEEP. ISSO PORQUE, DURANTE O PROCESSAMENTO DO CÓDIGO, A EXECUÇÃO PODE SER MAIS RÁPIDA DO
QUE O PROCESSO DOS PROGRAMAS NO DISPOSITIVO, ENTÃO SERÁ NECESSÁRIO RETARDAR ALGUMAS PARTES PARA GARANTIR QUE O AMBIENTE ESTEJA PRONTO PARA CONTINUAR O PROCESSO
'''
import pandas       as pd
'''
A BIBLIOTECA PANDAS É USADA PARA ANÁLISE DE DADOS. NÃO SERÁ APROFUNDADA AQUI, MAS É UMA FERRAMENTA EXTREMAMENTE ÚTIL E SERÁ USADA AQUI PARA FAZER A ABERTURA DO ARQUIVO ONDE ESTÃO OS
DADOS, COM O COMANDO A SEGUIR:
'''
dadosProd = pd.read_csv('produtos.csv')

'''
AGORA, FAREMOS A AUTOMATIZAÇÃO COM OS COMANDOS DO PYAUTOGUI

ALGUNS DOS COMANDOS SÃO:
PAUSE    -> DEFINE QUAL O TEMPO ENTRE CADA INTERVALO DE COMANDOS DO PYAUTOGUI
press    -> INDICA A PRESSA QUE SERÁ PRESSIONADA
write    -> INDICA QUAL TEXTO SERÁ DIGITADO
hotkey   -> USADO PARA PRESSIONAR UM COMANDO, COMO Ctrl + C, OU Ctrl + V
click    -> SIMULA O CLICK DO MOUSE. RECEBE A COORDENAÇÃO X E Y PARA INDICAR QUAL PONTO DA TELA O MOUSE SERÁ POSICIONADO PARA CLICAR
position -> INDICA A POSIÇÃO ATUAL DO MOUSE
drag     -> SIMULA O CLIQUE E ARRASTE DO MOUSE
'''

pa.PAUSE = 0.5
#ABRE A BARRA DE PESQUISA DO WINDOWS, PROCURA PELO SQL MANAGEMENT STUDIO E ABRE O PROGRAMA
pa.press('win')
pa.write('sql')
pa.press('enter')
#COLOCA UM TIMER DE 10 SEGUNDOS PARA O PROGRAMA CONTINUAR EXECUTANDO, PARA ESPERAR O PROGRAMA INICIAR
time.sleep(10)
#DENTRO DO SQL MANAGEMENT STUDIO, IRÁ FAZER O LOGIN NO USUÁRIO DO SISTEMA. COMO NO CASO DO MEU DISPOSITIVO, O LOGIN É FEITO JUNTO DO WINDOWS, NÃO É NECESSÁRIO INSERIR CREDENCIAIS
pa.press('enter')
#CTRL + N PARA ABRIR UMA NOVA ÁREA DE TRABALHO
pa.hotkey('ctrl', 'n')
#OUTRO TIMER, CASO A ÁREA DE TRABALHO DEMORE PARA ABRIR
time.sleep(5)
#CTRL + U PARA ABRIR A BARRA DE PESQUISA DOS BANCOS DE DADOS DISPONÍVEIS, 'BASE_TESTES' NESSE CASO, E FAZ A PROCURA POR ELE. O COMANDO PARA CRIAÇÃO DA TABELA EM QUESTÃO É:
'''
CREATE TABLE [dbo].[PRODHASHTAG](
	[CODIGO] [varchar](20) NOT NULL PRIMARY KEY,
	[MARCA] [varchar](50) NOT NULL,
	[TIPO] [varchar](50) NOT NULL,
	[CATEGORIA] [int] NOT NULL,
	[PRECOUNI] [float] NOT NULL,
	[CUSTO] [float] NOT NULL,
	[OBS] [varchar](100) NULL
)
'''
pa.hotkey('ctrl', 'u')
pa.write('BASE_TESTES')
pa.press('enter')
time.sleep(3)
#AUTOMATICAMENTE, O PROGRAMA JÁ IRÁ PRA ÁREA DE TRABALHO QUE FOR ABERTA, ENTÃO É SÓ INSERIR OS COMANDOS PARA INSERÇÃO DOS DADOS. PRIMEIRO, SERÃO EXCLUÍDOS OS DADOS DA TABELA
pa.write('DELETE FROM PRODHASHTAG')
pa.press('enter')
pa.press('enter')
for linha in dadosProd.index: #PERCORRE AS LINHAS DO ARQUIVO ONDE OS DADOS ESTÃO INSERIDOS
    #O MÉTODO .loc É USADO PARA ACESSAR UM LINHA OU COLUNAS ATRAVÉS DE SUAS LABELS, OU SEJA, SEUS NOMES. PRIMEIRO, FOI PASSADO A LINHA, QUE NESSE CASO, É A PRÓPRIA LINHA DO LAÇO FOR,
    #E DEPOIS FOI PASSADO A COLUNA ONDE SE ENCONTRA O VALOR, PASSANDO O NOME EXATO DAS COLUNAS DO ARQUIVO CSV
    codigo      = str(dadosProd.loc[linha, 'codigo'])
    marca       = str(dadosProd.loc[linha, 'marca'])
    tipo        = str(dadosProd.loc[linha, 'tipo'])
    categoria   = str(dadosProd.loc[linha, 'categoria'])
    precoUni    = str(dadosProd.loc[linha, 'preco_unitario'])
    custo       = str(dadosProd.loc[linha, 'custo'])
    obs         = str(dadosProd.loc[linha, 'obs'])
    
    if obs == 'nan':
        pa.write("INSERT INTO PRODHASHTAG VALUES ('"+codigo+"','"+marca+"','"+tipo+"','"+categoria+"','"+precoUni+"','"+custo+"','""')")
    else:
        pa.write("INSERT INTO PRODHASHTAG VALUES ('"+codigo+"','"+marca+"','"+tipo+"','"+categoria+"','"+precoUni+"','"+custo+"','"+obs+"')")
    pa.press('enter')

#DEPOIS DE SER FEITA A INCLUSÃO DO CÓDIGO, BASTA INSERIR OS DADOS NA TABELA COM F5
pa.press('f5')