'''
SÃO ESTRUTURAS DE DADOS QUE ARMAZENAM OS DADOS TAL COMO OS GALHOS DE UMA ÁRVORES, SE DIVIDINDO EM PONTOS CHAMADADOS 'NODES', QUE POR SUA VEZ POSSUEM DOIS NODES FILHOS, APENAS (POR ISSO BINÁRIO). O NODE FILHO DA ESQUERDA
SERÁ SEMPRE MENOR QUE O NODE PAI, ENQUANTO QUE O NODE FILHO DA DIREITO SERÁ SEMPRE MAIOR.
UMA DAS FORMAS DE FAZER A IMPLEMENTAÇÃO É A SEGUINTE:
'''