'''
ARGS E KWARGS SÃO FORMAS DE PASSAR ARGUMENTOS PARA UMA FUNÇÃO SEM QUE VOCÊ SAIBA REALMENTE QUANTOS ARGUMENTOS
SERÃO PASSADOS. DESSA FORMA, UTILIZANDO O COMANDO *, PARA ARGS, E **, PARA KWARGS, PODEM SER PASSADOS QUANTOS
ARGUMENTOS FOREM NECESSÁRIOS PARA A FUNÇÃO.
LEMBRANDO QUE OS NOMES ARGS E KWARGS SÃO CONVENÇÕES UTILIZADOS PELOS PROGRAMADORES EM PYTHON, MAS PODERIA SER
ATÉ MESMO *BANANA E **BANANAS, POR EXEMPLO, POIS O IMPORTANTE SÃO OS ASTERÍSCOS NO INÍCIO
'''

def somaNumeros(num1, num2, num3):
    resultado = num1 + num2 + num3
    return resultado

'''
NESSE CASO, FORAM DEFINIDOS 3 NÚMEROS QUE SERÃO PASSADOS PARA DENTRO DA FUNÇÃO. SEM DEFINIR VALOR PADRÃO PARA ELES
CASO ALGUM NÃO SEJA PASSADO, OU CASO SEJA PASSADO ALGUM VALOR ALÉM DOS 3 DEFINIDOS, A FUNÇÃO RETORNARÁ UM ERRO.
AGORA IMAGINE QUE VOCÊ QUEIRA SOMAR QUANTOS NÚMEROS FOREM NECESSÁRIOS, VOCÊ PODERIA PASSÁ-LOS PARA A FUNÇÃO
UTILIZANDO O *ARGS
'''

def somaNumerosArgs(*args):
    resultado: 0
    for num in args:
        resultado += num
    return resultado

somaNumerosArgs(1,2,5,10,50,7,9,20)
'''
ARGS FUNCIONAM GERANDO UMA TUPLA DOS VALORES QUE SÃO PASSADOS PARA DENTRO DA FUNÇÃO, POR ISSO É UTILIZADO UM LAÇO
DE REPETIÇÃO PARA TRATAR TAIS VALORES

JÁ OS KWARGS FUNCIONAM DE FORMA SEMELHANTE, PORÉM ELES FUNCIONAM COMO PASSAGEM DE ARGUMENTOS POR CHAVE, E NÃO 
POR POSIÇÃO. PEGANDO O EXEMPLO DA FUNÇÃO 'somaNumeros', AS PASSAGENS DE VALORES SERIAM DA SEGUINTE FORMA:

somaNumeros(1,2,3) -> OS VALORES SÃO PASSADOS NA ORDEM EM QUE OS ARGUMENTOS SÃO DEFINIDOS NA FUNÇÃO, ENTÃO num1
                      RECEBE O VALOR 1, num2 RECEBE O VALOR 2 E num3 RECEBE O VALOR 3

somaNumeros(num1 = 3, num3 = 1, num2 = 2) -> AQUI, OS VALORES SÃO PASSADOS COMO CHAVE-VALOR, ENTÃO NÃO É NECESSÁRIO
                                             SEGUIR A ORDEM EM QUE OS VALORES SÃO PASSADOS, CONTANDO QUE VOCÊ
                                             FAÇA A REFERÊNCIA DA CHAVE DO ARGUMENTO COM SEU VALOR

É PRECISO TER CUIDADO QUANDO FOR MISTURAR OS DOIS TIPOS NA CHAMADO DE UMA FUNÇÃO, POIS ELES SEMPRE OBEDECEM A ORDEM
DE PASSAGENS POR POSIÇÃO PRIMEIRO E PASSAGENS POR CHAVE EM SEGUNDO
'''