'''
RECUSÃO É UMA FORMA ELEGANTE DE RESOLVER PROBLEMAS, CHAMANDO UMA FUNÇÃO DENTRO DE SI MESMA. AS FUNÇÕES QUE FAZEM ESSE PROCESSO SÃO CHAMADAS DE FUNÇÕES RECURSIVAS, ENQUANTO QUE O ATO
DE CHAMAR A SI MESMA É UMA RECURSÃO.
EM GERAL, OS PROBLEMAS TRATADOS EM RECUSÃO PODEM SER TRATADOS DE OUTRAS FORMAS, COMO UM LAÇO DE REPETIÇÃO. MAS, COMO FOI DITO, RESOLVER ESSE MESMO PROBLEMA ATRAVÉS DE UMA FUNÇÃO
RECURSIVA PODE SER MAIS ELEGANTE E LEGÍVEL
'''
def fatorial(numero):
    if numero <= 1:
        return numero
    else:
        return numero * fatorial(numero - 1)
    
print(fatorial(4))

'''
CADA CHAMADA DA FUNÇÃO ALOCA UM NOVO ESPAÇO NA MEMÓRIA, POR ISSO NÃO É OCASIONADO NENHUM ERRO, POR EXEMPLO, AO DECLARAR NOVAS VARIÁVEIS COM O MESMO NOME. OUTRA COISA QUE VALE A PENA 
SER COMENTADA É QUE, DURANTE AS CHAMADAS RECURSIVAS, É FORMADA UMA PILHA (STACK), PORTANTO OS RETORNOS SERÃO NO FORMATO LIFO (LAST IN, FIRST OUT).
EX:
NA FUNÇÃO ACIMA, PARA DESCOBRIR O FATORIAL DE UM NÚMERO, QUANDO É PASSADO O NÚMERO 4 DE EXEMPLO, AS CHAMADAS DA FUNÇÃO SERÃO FEITAS COM OS NÚMEROS 4, 3, 2 E 1, E OS SEUS RETORNOS SERÃO
1, 2, 6 E 24, RESPECTIVAMENTE
'''