'''
RECUSÃO É UMA FORMA ELEGANTE DE RESOLVER PROBLEMAS, CHAMANDO UMA FUNÇÃO DENTRO DE SI MESMA. AS FUNÇÕES QUE FAZEM ESSE PROCESSO SÃO CHAMADAS DE FUNÇÕES RECURSIVAS, ENQUANTO QUE O ATO
DE CHAMAR A SI MESMA É UMA RECURSÃO.
EM GERAL, OS PROBLEMAS TRATADOS EM RECUSÃO PODEM SER TRATADOS DE OUTRAS FORMAS, COMO UM LAÇO DE REPETIÇÃO. MAS, COMO FOI DITO, RESOLVER ESSE MESMO PROBLEMA ATRAVÉS DE UMA FUNÇÃO
RECURSIVA PODE SER MAIS ELEGANTE E LEGÍVEL
'''
def fatorial(numero):
    if numero <= 1:
        return numero
    else:
        return numero * fatorial(numero - 1)
    
print(fatorial(4))