'''
CRIE UMA FUNÇÃO QUE RECEBE DUAS LISTAS DE GOLS MARCADOS E SOFRIDOS POR UM TIME DE FUTEBOL, CALCULE A PONTUAÇÃO E O PERCENTUAL DE APROVEITAMENTO DO TIME. AS VITÓRIAS (GOLS MARCADOS > GOLS SOFRIDOS) VALEM 3 PONTOS, OS EMPATES (GOLS MARCADOS = GOLS SOFRIDOS), E AS DERROTAS (GOLS MARCADOS < GOLS SOFRIDOS) NÃO VALEM NADA.
'''
gols_marcados = [2, 1, 3, 1, 0]
gols_sofridos = [1, 2, 2, 1, 3]

